/**
 * controllers/schema.controller.ts — Form Schema HTTP Handler
 *
 * Serves the scraped/static form schema that the frontend uses
 * to dynamically render form fields.
 *
 * TODO: Add Redis caching so schema is not read from disk on every request.
 * TODO: Add ETags for client-side caching.
 */

import { Request, Response, NextFunction } from 'express';
import path from 'path';
import fs from 'fs';
import { sendSuccess, sendError } from '../utils/response';
import { HTTP_STATUS } from '../constants';
import { logger } from '../logger/logger';
import { FormSchema } from '../types';

// Resolve schema.json path relative to project root
// (Generated by the scraper module into scraper/output/schema.json)
const SCHEMA_FILE_PATH = path.resolve(
  __dirname,
  '../../../scraper/output/schema.json'
);

// ── GET /api/schema ──────────────────────────────────────────────────────────

export const getSchemaController = (
  req: Request,
  res: Response,
  next: NextFunction
): void => {
  try {
    if (!fs.existsSync(SCHEMA_FILE_PATH)) {
      logger.warn('schema.json not found — serving fallback schema', {
        expectedPath: SCHEMA_FILE_PATH,
      });
      // Serve a built-in fallback schema so the frontend always works
      sendSuccess(res, 'Form schema loaded (fallback)', getFallbackSchema());
      return;
    }

    const raw = fs.readFileSync(SCHEMA_FILE_PATH, 'utf-8');
    const schema: FormSchema = JSON.parse(raw) as FormSchema;

    logger.info('Serving form schema', { version: schema.version });
    sendSuccess(res, 'Form schema loaded', schema);
  } catch (error) {
    next(error);
  }
};

// ── Fallback Schema ──────────────────────────────────────────────────────────
// Used when scraper hasn't been run yet. Mirrors the real Udyam portal fields.

const getFallbackSchema = (): FormSchema => ({
  version: '1.0.0',
  scrapedAt: new Date().toISOString(),
  source: 'fallback',
  steps: [
    {
      step: 1,
      title: 'Aadhaar Verification',
      description: 'Enter your Aadhaar details to verify your identity',
      fields: [
        {
          id: 'aadhaarNumber',
          name: 'aadhaarNumber',
          label: 'Aadhaar Number',
          type: 'text',
          placeholder: 'Enter 12-digit Aadhaar Number',
          required: true,
          step: 1,
          validation: {
            pattern: '^\\d{12}$',
            minLength: 12,
            maxLength: 12,
          },
        },
        {
          id: 'aadhaarName',
          name: 'aadhaarName',
          label: 'Name as per Aadhaar',
          type: 'text',
          placeholder: 'Enter name exactly as on Aadhaar card',
          required: true,
          step: 1,
          validation: {
            minLength: 2,
            maxLength: 100,
          },
        },
      ],
    },
    {
      step: 2,
      title: 'PAN Verification',
      description: 'Enter your PAN and organisation details',
      fields: [
        {
          id: 'organisationType',
          name: 'organisationType',
          label: 'Type of Organisation',
          type: 'select',
          placeholder: 'Select Organisation Type',
          required: true,
          step: 2,
          validation: {
            options: [
              { value: 'PROPRIETORSHIP', label: 'Proprietorship' },
              { value: 'PARTNERSHIP', label: 'Partnership Firm' },
              { value: 'HUF', label: 'Hindu Undivided Family (HUF)' },
              { value: 'PRIVATE_LIMITED', label: 'Private Limited Company' },
              { value: 'PUBLIC_LIMITED', label: 'Public Limited Company' },
              { value: 'LLP', label: 'Limited Liability Partnership' },
              { value: 'CO_OPERATIVE', label: 'Co-operative Societies' },
              { value: 'SELF_HELP_GROUP', label: 'Self Help Group' },
              { value: 'OTHER', label: 'Others' },
            ],
          },
        },
        {
          id: 'panNumber',
          name: 'panNumber',
          label: 'PAN Number',
          type: 'text',
          placeholder: 'Enter 10-digit PAN (e.g., ABCDE1234F)',
          required: true,
          step: 2,
          validation: {
            pattern: '^[A-Z]{5}[0-9]{4}[A-Z]{1}$',
            minLength: 10,
            maxLength: 10,
          },
        },
        {
          id: 'panHolderName',
          name: 'panHolderName',
          label: 'Name of PAN Holder',
          type: 'text',
          placeholder: 'Enter name exactly as on PAN card',
          required: true,
          step: 2,
          validation: { minLength: 2, maxLength: 100 },
        },
        {
          id: 'dobOrDoi',
          name: 'dobOrDoi',
          label: 'Date of Birth / Date of Incorporation as per PAN',
          type: 'date',
          placeholder: 'YYYY-MM-DD',
          required: true,
          step: 2,
        },
      ],
    },
  ],
});
